### ISSUE TITLE
DFP-34X-2C2 becomes unresponsive after a few days

### ISSUE THREAD

**Issue by labuwx** [Anime4000/RTL960x#189]
I have a DFP-34X-2C2 with firmware 220923. It gets progressively unresponsive after 5 days of uptime.
First the web interface started to respond slowly, then not at all. Soon after that it would not even respond to ping. Access to my ISP and to the internet is unhindered (bandwidth and latency wise) but I do not know if OMCI communication is affected.

Suspecting a memory leak, I made a light version of 220923 with no boa, igmpd, dhcpd, ssh, ... . I only had telnet, omci_app, pondetect, configd running. I was monitoring the memory usage and did not see any increase over the days. /proc/kmsg did not show anything.
Yet after 5 days of uptime it started again. First diag decided to take 10 seconds to start up, while other command line tools did work normally. Then I could not even connect with telnet, finally no response to pings.

Has anybody experienced this? Anybody from the opposite, still stable after months of uptime group? 

The stick is in a well ventilated rack, max 45C transceiver temperature.
The traffic is not extreme either. There is a constant ~150 Mb/s IPTV downstream that the ONU should forward. Besides that, the internet traffic is usually below 10 Mb/s with less than 100 Mb/s peaks.

**Comment by ToTheCLI** [comment]
> It gets progressively unresponsive after 5 days of uptime.

Similar issues happened to me (Packet loss with pings), switched to Lantiq based GPON SFPs and never observed this issue.

What OLT do you have and what is the SFP plugged in to?

**Comment by labuwx** [comment]
> What OLT do you have and what is the SFP plugged in to?

The OLT reports itself as HWTC (and probably really is). I use a gigabit switch (TL-SG2424) but the same happens when I bypass the switch and plug the ONU into my router via a gigabit media converter.

> Similar issues happened to me (Packet loss with pings), switched to Lantiq based GPON SFPs and never observed this issue.

Just to reiterate, the ONU did not stop forwarding anything between my ISP and my LAN, it's just the user interface (and other higher level services) that went down. However I am afraid that complete loss of connection would happen if I left the ONU running for long enough. Either because the lower layers of the RTL9601 would need some input from the locked up upper layers, or the ONU would stop responding to OMCI and my ISP would terminate my connection.

I used to have a UFiber NanoG (Broadcom chipset) but I could not get the IPTV multicast forwarded. Is it accessible with Lantiq ONUs?
My current setup with the DFP-34X-2C2 is not ideal either. I would like to use IGMP snooping on the ONU since the full IPTV downstream takes up a significant portion of the gigabit link to my switch but I suspect (have not confirmed) that would need igmpd, which dies with the rest of the services.

**Comment by ToTheCLI** [comment]
![Screenshot 2023-08-27 181936](https://github.com/Anime4000/RTL960x/assets/88133373/c35387bd-a197-427f-8b12-779bf1967e83)
Well there are settings for IGMP in Lantiq SFP's Chinese firmware, don't have IPTV to test with though.

**Comment by ToTheCLI** [comment]
> The OLT reports itself as HWTC

Best for them is MA5671A or fs.com SFPs.

**Comment by labuwx** [comment]
I think I have found the culprit. I had OMCI_LOGFILE and OMCI_LOGFILE_MASK set.
With the aforementioned parameters cleared, my ONU has been up and responsive for 20 days now.

**Comment by rndm2** [comment]
I have exactly the same problem. But instead of days, I have hours, or even minutes.
And it causes random packet loss.

Here is the `top` from stick:
<img width="865" alt="Screenshot 2023-11-17 at 21 56 38" src="https://github.com/Anime4000/RTL960x/assets/6842505/1fca4b6d-2a8a-4026-94a6-d43137aa964e">

Config: 
`
# flash all
<Config Name="ROOT">
 <Dir Name="HW_MIB_TABLE">
  <Value Name="SUPER_NAME" Value="adsl"/>
  <Value Name="SUPER_PASSWORD" Value="realtek"/>
  <Value Name="TEST_MAC_ADDR" Value="realtek"/>
  <Value Name="ELAN_MAC_ADDR" Value="00e04c867001"/>
  <Value Name="WLAN_MAC_ADDR" Value="00e04c076802"/>
  <Value Name="MAC_KEY" Value=""/>
  <Value Name="RESTORE_DEFAULT_EN" Value="1"/>
  <Value Name="WAN_PHY_PORT" Value="4"/>
  <Value Name="LASER_POLARITY_TYPE" Value="0"/>
  <Value Name="PON_DETECT_ENABLE" Value="1"/>
  <Value Name="HW_RF_TYPE" Value="7"/>
  <Value Name="HW_WLAN0_TX_POWER_CCK_A" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="HW_WLAN0_TX_POWER_CCK_B" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="HW_WLAN0_TX_POWER_HT40_1S_A" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="HW_WLAN0_TX_POWER_HT40_1S_B" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="HW_WLAN0_TX_POWER_DIFF_HT40_2S" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="HW_WLAN0_TX_POWER_DIFF_HT20" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="HW_WLAN0_TX_POWER_DIFF_OFDM" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="HW_WLAN0_11N_TSSI1" Value="0"/>
  <Value Name="HW_WLAN0_11N_TSSI2" Value="0"/>
  <Value Name="HW_WLAN0_11N_THER" Value="0"/>
  <Value Name="HW_WLAN0_11N_THER_2" Value="0"/>
  <Value Name="HW_WLAN0_11N_PA_TYPE" Value="0"/>
  <Value Name="HW_WLAN0_REG_DOMAIN" Value="1"/>
  <Value Name="HW_WLAN0_11N_TRSWITCH" Value="0"/>
  <Value Name="HW_WLAN0_11N_TRSWPAPE_C9" Value="0"/>
  <Value Name="HW_WLAN0_11N_TRSWPAPE_CC" Value="0"/>
  <Value Name="HW_ANT_DIVERSITY" Value="0"/>
  <Value Name="HW_TX_ANT" Value="0"/>
  <Value Name="HW_CS_THRESHOLD" Value="11"/>
  <Value Name="HW_CCA_MODE" Value="1"/>
  <Value Name="HW_PHY_TYPE" Value="0"/>
  <Value Name="HW_WLAN_LED_TYPE" Value="7"/>
  <Value Name="BYTE" Value="255"/>
  <Value Name="WORD" Value="65535"/>
  <Value Name="DWORD" Value="4294967295"/>
  <Value Name="INT1" Value="2147483647"/>
  <Value Name="INT2" Value="-2147483648"/>
  <Value Name="WIFI_SUPPORT" Value="0"/>
  <Value Name="HW_SERIAL_NO" Value="000000000002"/>
  <Value Name="HW_FON_KEYWORD" Value="63,62,68,4a,75,3c,65,cd,7b,75,e5,2d,a9,80,72,8c,97,fc,bd,9b,37,51,d9,e3,82,92,68,a1,07,ae,a0,b5"/>
  <Value Name="HW_WLAN0_11N_XCAP" Value="0"/>
  <Value Name="HW_WLAN0_11N_XCAP_2" Value="0"/>
  <Value Name="HW_WLAN0_11N_TARGET_PWR" Value="0"/>
  <Value Name="HW_WLAN0_COUNTRYCODE" Value="1"/>
  <Value Name="HW_WLAN1_COUNTRYCODE" Value="1"/>
  <Value Name="HW_WLAN0_COUNTRYSTR" Value="US"/>
  <Value Name="HW_WLAN1_COUNTRYSTR" Value="US"/>
  <Value Name="HW_CWMP_MANUFACTURER" Value="MSTC"/>
  <Value Name="HW_CWMP_PRODUCTCLASS" Value="HGU"/>
  <Value Name="HW_HWVER" Value="GPT-2541GNAC"/>
  <Value Name="GPON_ONU_MODEL" Value="HGU"/>
  <Value Name="LAN_SDS_MODE" Value="1"/>
  <Value Name="PON_MODE" Value="1"/>
  <Value Name="PON_LED_SPEC" Value="0"/>
  <Value Name="OUI" Value="11,11,11"/>
  <Value Name="PORT_REMAPPING" Value="00,01,00,00"/>
  <Value Name="PON_VENDOR_ID" Value="MSTC"/>
  <Value Name="GPON_SN" Value="MSTC13DA1366"/>
  <Value Name="EPON_ONU_MODEL" Value="MSTC"/>
  <Value Name="EPON_EXTONU_MODEL" Value="HGU"/>
  <Value Name="EPON_SILENT_MODE" Value="1"/>
 </Dir>
</Config>
<Config Name="ROOT">
 <Dir Name="MIB_TABLE">
  <Value Name="WAN_MODE" Value="7"/>
  <Value Name="LAN_IP_ADDR" Value="10.10.100.100"/>
  <Value Name="LAN_SUBNET" Value="255.255.255.0"/>
  <Value Name="LAN_ENABLE_IP2" Value="0"/>
  <Value Name="LAN_IP_ADDR2" Value="192.168.100.1"/>
  <Value Name="LAN_SUBNET2" Value="255.255.255.0"/>
  <Value Name="LAN_RIP" Value="0"/>
  <Value Name="LAN_AUTOSEARCH" Value="0"/>
  <Value Name="DNS_MODE" Value="0"/>
  <Value Name="DNS1" Value="0.0.0.0"/>
  <Value Name="DNS2" Value="0.0.0.0"/>
  <Value Name="DNS3" Value="0.0.0.0"/>
  <Value Name="ADSL_MODE" Value="83"/>
  <Value Name="ADSL_OLR" Value="3"/>
  <Value Name="USER_NAME" Value="user"/>
  <Value Name="USER_PASSWORD" Value="user"/>
  <Value Name="DEVICE_TYPE" Value="0"/>
  <Value Name="INIT_LINE" Value="1"/>
  <Value Name="INIT_SCRIPT" Value="1"/>
  <Value Name="SNMP_SYS_NAME" Value="Modem/Router"/>
  <Value Name="VC_AUTOSEARCH" Value="0"/>
  <Value Name="BR_AGEING_TIME" Value="7200"/>
  <Value Name="BR_STP_ENABLED" Value="0"/>
  <Value Name="MP_MODE" Value="4"/>
  <Value Name="SPC_ENABLED" Value="0"/>
  <Value Name="SPC_IPTYPE" Value="0"/>
  <Value Name="MP_FIN" Value="1"/>
  <Value Name="MULTI_LINGUAL_STATE" Value="en"/>
  <Value Name="TFTP_SERVER_ADDR" Value="tftp://0.0.0.0"/>
  <Value Name="POSIX_TZ_STRING" Value=""/>
  <Value Name="BOOT_FILENAME" Value=""/>
  <Value Name="UPNP" Value="0"/>
  <Value Name="UPNP_EXT_ITF" Value="255"/>
  <Value Name="SYSLOG_LOG_LEVEL" Value="0"/>
  <Value Name="SYSLOG_DISPLAY_LEVEL" Value="0"/>
  <Value Name="SUSER_NAME" Value="admin"/>
  <Value Name="SUSER_PASSWORD" Value=""/>
  <Value Name="E8BDUSER_NAME" Value="administrator"/>
  <Value Name="E8BDUSER_PASSWORD" Value="Stel$864"/>
  <Value Name="ADSL_TONE" Value="00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00"/>
  <Value Name="DIRECT_BRIDGE_MODE" Value="1"/>
  <Value Name="ADSL_HIGH_INP" Value="0"/>
  <Value Name="SYSLOG" Value="0"/>
  <Value Name="MAXLOGLEN" Value="16384"/>
  <Value Name="ADSLDBG" Value="0"/>
  <Value Name="MIB_ETH_MAC_CTRL" Value="0"/>
  <Value Name="MIB_WLAN_MAC_CTRL" Value="0"/>
  <Value Name="SNOOPING_ENABLED" Value="0"/>
  <Value Name="LOID" Value=""/>
  <Value Name="LOID_PASSWD" Value=""/>
  <Value Name="LOID_OLD" Value=""/>
  <Value Name="LOID_PASSWD_OLD" Value=""/>
  <Value Name="PROVINCE_TRAP_PPPOE_TRAFFIC" Value="0"/>
  <Value Name="GPON_PLOAM_FORMAT" Value="0"/>
  <Value Name="GPON_PLOAM_PASSWD" Value=""/>
  <Value Name="OMCI_DBGLVL" Value="0"/>
  <Value Name="OMCI_LOGFILE" Value="0"/>
  <Value Name="OMCI_PORT_TYPE" Value="1"/>
  <Value Name="DUAL_MGMT_MODE" Value="1"/>
  <Value Name="OMCI_CUSTOM_BDP" Value="258"/>
  <Value Name="OMCI_CUSTOM_RDP" Value="4"/>
  <Value Name="OMCI_CUSTOM_MCAST" Value="0"/>
  <Value Name="OMCI_CUSTOM_ME" Value="65536"/>
  <Value Name="OMCI_VENDOR_PRODUCT_CODE" Value="15"/>
  <Value Name="OMCI_FAKE_OK" Value="1"/>
  <Value Name="OMCI_VEIP_SLOT_ID" Value="255"/>
  <Value Name="OMCI_WAN_QOS_QUEUE_NUM" Value="1"/>
  <Value Name="RTK_IGMP_DBGEN" Value="0"/>
  <Value Name="RTK_IGMP_DROPV1" Value="0"/>
  <Value Name="RTK_IGMP_VIDTYPE" Value="0"/>
  <Value Name="RTK_IGMP_TAGDECISION" Value="0"/>
  <Value Name="VLAN_CFG_TYPE" Value="0"/>
  <Value Name="VLAN_MANU_MODE" Value="0"/>
  <Value Name="VLAN_MANU_TAG_VID" Value="65535"/>
  <Value Name="VLAN_MANU_TAG_PRI" Value="255"/>
  <Value Name="OMCI_OLT_MODE" Value="0"/>
  <Value Name="OMCI_SW_VER1" Value="V1.7.1"/>
  <Value Name="OMCI_SW_VER2" Value="V1.7.1"/>
  <Value Name="OMCC_VER" Value="128"/>
  <Value Name="OMCI_TM_OPT" Value="2"/>
  <Value Name="OMCI_LOGFILE_MASK" Value="0"/>
  <Value Name="REBOOT_TIME" Value="0"/>
  <Value Name="DHCP_PORT_FILTER" Value="1"/>
  <Value Name="NTP_EXT_ITF" Value="65535"/>
  <Value Name="FIBER_MODE" Value="0"/>
  <Value Name="RTK_DEVID_MANUFACTURER" Value=""/>
  <Value Name="RTK_DEVID_OUI" Value=""/>
  <Value Name="RTK_DEVID_PRODUCTCLASS" Value=""/>
  <Value Name="RTK_DEVINFO_SPECVER" Value=""/>
  <Value Name="RTK_DEVINFO_SWVER" Value=""/>
  <Value Name="RTK_DEVINFO_HWVER" Value=""/>
  <Value Name="DEVICE_NAME" Value="RTK_GW"/>
 </Dir>
 <Dir Name="ATM_VC_TBL">
 </Dir>
 <Dir Name="SW_PORT_TBL"> 
  <Value Name="PVCInterface" Value="65535"/>
  <Value Name="InterfaceGroup" Value="0"/>
  <Value Name="PVID" Value="0"/>
  <Value Name="LinkMode" Value="4"/>
  <Value Name="VLAN on LAN Enabled" Value="0"/>
  <Value Name="VLAN on LAN InterfaceGroup" Value="0"/>
  <Value Name="VID" Value="0"/>
 </Dir>
 <Dir Name="SW_PORT_TBL"> 
  <Value Name="PVCInterface" Value="65535"/>
  <Value Name="InterfaceGroup" Value="0"/>
  <Value Name="PVID" Value="1"/>
  <Value Name="LinkMode" Value="4"/>
  <Value Name="VLAN on LAN Enabled" Value="0"/>
  <Value Name="VLAN on LAN InterfaceGroup" Value="0"/>
  <Value Name="VID" Value="0"/>
 </Dir>
 <Dir Name="MAC_BASE_DHCP_TBL">
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="0"/>
  <Value Name="VCI" Value="35"/>
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="8"/>
  <Value Name="VCI" Value="35"/>
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="0"/>
  <Value Name="VCI" Value="43"/>
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="0"/>
  <Value Name="VCI" Value="51"/>
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="0"/>
  <Value Name="VCI" Value="59"/>
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="8"/>
  <Value Name="VCI" Value="43"/>
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="8"/>
  <Value Name="VCI" Value="51"/>
 </Dir>
 <Dir Name="AUTO_PVC_SEARCH_TBL"> 
  <Value Name="VPI" Value="8"/>
  <Value Name="VCI" Value="59"/>
 </Dir>
 <Dir Name="PPPOE_SESSION_TBL">
 </Dir>
 <Dir Name="RIP_TBL">
 </Dir>
 <Dir Name="DHCP_RESERVED_IPADDR_TBL">
 </Dir>
 <Dir Name="EPON_LLID_TBL">
 </Dir>
</Config>
`
