### ISSUE TITLE
Need for improved documentation on graphical interface integration

### ISSUE THREAD

**Issue by libr3** [Anime4000/RTL960x#308]
One of the common issues in creating this type of project (reverse engineering or, indeed, in the world of Free Software) is the lack of adequate documentation that does not assume the reader knows a lot about the area.

Better documentation is needed, in my honest opinion. Additionally, information on how to perform certain procedures is scattered throughout the repository without a coherent connection between them.

I will focus on what confuses me: apparently, it is possible to change the graphical interface.

In my case, I am using a DFP-34X-2C2.

First, I go to the WebGui [1] folder of the project where I find that it is now possible to use a much better HTML5 interface than the default one. Then I find that the information on how to install it is located in the Firmware_Mod [2] folder for some reason, and that for that folder to be useful I have to go to the emulator [3] subfolder within the Tools [4] folder.

My question is: how do I "copy and paste the relevant code" [5]? How can I integrate the graphical interface presented in the Firmware_Mod folder with WebGui and install it with what is found in the emulator folder? And how can I set the wallpaper I want as seen in the examples [6] (examples that are very good for seeing the result but do not explain anything)?

The ".md" files assume too much.

[1] https://github.com/Anime4000/RTL960x/tree/main/WebGui
[2] https://github.com/Anime4000/RTL960x/tree/main/Firmware_Mod
[3] https://github.com/Anime4000/RTL960x/tree/main/Tools/emulator
[4] https://github.com/Anime4000/RTL960x/tree/main/Tools
[5] https://github.com/Anime4000/RTL960x/blob/240ba0c4053c5c7eee9729ef1bca37e0e43623dc/Firmware_Mod/README.md?plain=1#L13
[6] https://github.com/Anime4000/RTL960x/blob/main/Firmware_Mod/README.md#webgui

**Comment by Anime4000** [comment]
First of all, I am sorry about incomplete documentation, still many file that I not committed yet or publish:

One reason is my Web Design not that good 😅 even I fork off from V2801F WebGUI project and trying to mimicking OpenWRT layout which is far from like look of it.

Then, I not sure how to run boa in x86 VM to render how it look like. Since no WYSIWYG editor for boa based, mistake can kill the SFP Stick and keep writing to NAND Flash also not good idea.

As for now I use Apache HTTP and mark `*.asp` as normal HTML for now

Then, I still don't know how to compile uClibc MIPS, we have tried and still print `illegal instruction (core dumped)`

Unlike D-Link DPN-FX3060V that use ARM64 RTL9607DQ, quite easy to compile as simply use Ubuntu 19.10 and arm64 compile...

Because of can't compile to add our own code, many of us simply use dumb looping `*.sh` script, not perfect and not nice with processor time but it get the job done atleast

What I can do for now, I have updated the **RTL960x Emulator** `README.md`
